# Física Computacional II - Tarea 2

Nombre: Sofia Catalina Soto Ferrada

Rut: 22.261.514-3

### Pregunta 1

In [3]:
import numpy as np

In [5]:
# Elegi 12 como semilla para que los resultados sean reproducibles

rng = np.random.default_rng(seed = 12)

In [6]:
# Defino las luminosidades de las estrellas en unidades de luminosidad solar y las distancias en parsec

L = np.array([1.0, 2.5, 0.8, 5.0, 10.0])
d = np.array([10, 25, 15, 40, 60])
L, d

(array([ 1. ,  2.5,  0.8,  5. , 10. ]), array([10, 25, 15, 40, 60]))

In [7]:
# Constantes para convertir las unidades
L_solar = 3.828e26 # luminosidad solar a watts definido como L_solar
pc = 3.08e16 # Parsec definido como pc
def calcular_flujo(L, d):
    # Convierto la luminosidad solar a watts
    L = L * L_solar
    
    # Convierto la distancia de parsec a metros
    d = d * pc
    
    # Calculo el flujo observado
    F = L / (4 * np.pi * d**2)
    
    return F
F = calcular_flujo(L, d)

L, d, F

(array([ 1. ,  2.5,  0.8,  5. , 10. ]),
 array([10, 25, 15, 40, 60]),
 array([3.21115029e-10, 1.28446012e-10, 1.14174233e-10, 1.00348447e-10,
        8.91986192e-11]))

In [8]:
# Indices de mayor o menor flujo
indice_mayor = np.argmax(F)

indice_menor = np.argmin(F)

indice_mayor, indice_menor

(np.int32(0), np.int32(4))

In [9]:
# Promedio y mediana del flujo
flujo_promedio = np.mean(F)

flujo_mediana = np.median(F)

flujo_promedio, flujo_mediana

(np.float64(1.5065646775634134e-10), np.float64(1.1417423252108758e-10))

In [10]:
# Defino el límite de detección
limite_deteccion = 1e-11

# Creo una máscara para las estrellas detectables
detectadas = F >= limite_deteccion

detectadas

array([ True,  True,  True,  True,  True])

In [11]:
# Busco los índices de las estrellas detectadas
indices_detectadas = np.where(detectadas)[0]
indices_detectadas

array([0, 1, 2, 3, 4])

In [13]:
# Ordeno los índices según el flujo, de mayor a menor
flujos_ordenados = np.sort(F)[::-1]
flujos_ordenados

array([3.21115029e-10, 1.28446012e-10, 1.14174233e-10, 1.00348447e-10,
       8.91986192e-11])

### Pregunta 2

In [21]:
# Creo 500 tiempos equidistantes entre 0 y 10 años
t = np.linspace(0, 10, 500)

# Creo un flujo normalizado igual a 1
flujo = np.ones(500)

# Agrego ruido gaussiano
ruido = rng.normal(loc=0, scale=0.002, size=500)

# Agrego el ruido al flujo
flujo = flujo + ruido

# Identifico los puntos que están dentro del intervalo del tránsito
transito = (t >= 4.5) & (t <= 5.0)

# Disminuyo el flujo durante el tránsito
flujo[transito] = flujo[transito] - 0.02

In [22]:
# Calculo el flujo promedio
flujo_promedio = np.mean(flujo)
flujo_promedio

np.float64(0.9990258215869314)

In [23]:
# Calculo la desviación estándar del flujo
desviacion = np.std(flujo)
desviacion

np.float64(0.0048643131046462555)

In [26]:
# Busco el valor mínimo del flujo
flujo_minimo = np.min(flujo)

# Busco el índice donde ocurre el mínimo
indice_minimo = np.argmin(flujo)

flujo_minimo, indice_minimo

(np.float64(0.9767278292932017), np.int32(237))

In [27]:
# Busco el tiempo correspondiente al valor mínimo
tiempo_minimo = t[indice_minimo]

tiempo_minimo

np.float64(4.749498997995992)

In [28]:
# Calculo el límite de 3 sigma
limite_3sigma = flujo_promedio - 3 * desviacion

# Selecciono los puntos que cumplen la condición
puntos_transito = flujo < limite_3sigma

puntos_transito

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,

In [30]:
# Cuento los puntos identificados como posibles puntos del tránsito
cantidad_puntos= np.sum(puntos_transito)

cantidad_puntos

np.int32(24)

In [31]:
# Calculo el flujo promedio durante el tránsito
flujo_transito = np.mean(flujo[transito])

# Calculo la profundidad del tránsito
profundidad = 1 - flujo_transito

profundidad

np.float64(0.020277386242273376)

In [32]:
# Calculo la razón entre el radio del planeta y el radio de la estrella
razon_radios = np.sqrt(profundidad)

razon_radios

np.float64(0.14239868764238445)

In [33]:
# Obtengo los tiempos de los puntos identificados
tiempos_detectados = t[puntos_transito]

tiempos_detectados

array([4.50901804, 4.52905812, 4.5490982 , 4.56913828, 4.58917836,
       4.60921844, 4.62925852, 4.6492986 , 4.66933868, 4.68937876,
       4.72945892, 4.749499  , 4.76953908, 4.78957916, 4.80961924,
       4.82965932, 4.8496994 , 4.86973948, 4.88977956, 4.90981964,
       4.92985972, 4.9498998 , 4.96993988, 4.98997996])

In [45]:
# El intervalo original del tránsito fue entre 4.5 y 5.0 años.
# Comparo este intervalo con los tiempos encontrados usando el criterio de 3 sigma.